project:
  type: website
  output-dir: docs
  resources:
    - assets/

website:
  title: "DigiKat"
  site-url: https://lusiki.github.io/DigiKat/
  navbar:
    left:
      - text: "Osnovne informacije"
        href: pages/index.qmd
      - text: "O projektu"
        href: pages/about.qmd
      - text: "Projektni raspored"
        href: pages/schedule.qmd
      - text: "Baza podataka"
        href: pages/baza.qmd
      - text: "Mapa medijskog prostora"
        menu:
          - text: "Mapa ekosustava"
            href: pages/mapa/mapa.qmd
          - text: "Tematske struje"
            href: pages/mapa/mapa_stats.qmd
          - text: "Atmosfera diskursa"
            href: pages/mapa/diskurs.qmd
          - text: "Fokus na događaje i kampanje"
            href: pages/mapa/događaji.qmd
      - text: "Tematska istraživanja"
        menu:
          - text: "Analiza self-help sadržaja na YouTube-u"
            href: ""
          - text: "Hodočasnički turizam"
            href: ""
          - text: "Demokršćanstvo"
            href: ""
          - text: "Katoličko obrazovanje"
            href: ""
          - text: "Prikazivanje katoličkih svetaca i svetica"
            href: ""
      - text: "Obavijesti"
        href: pages/news.qmd
      - text: "Resursi"
        href: pages/resources.qmd
    right:
      - text: "O stranici"
        href: pages/site-info.qmd
      - icon: github
        href: https://github.com/lusiki/DigiKat

format:
  html:
    theme: cosmo
    css: 
      - assets/css/style.css
      - assets/css/custom.scss
    toc: true
    toc-location: left
    code-fold: show
    code-tools: true
    mainfont: system-ui